#!/usr/bin/env bash

wiring_file='wiring'
while getopts "hrw:" arg; do
  case $arg in
    h*)
      echo "Parameters:"
      echo "-w NAME  use/create wiring+config NAME (default: wiring = the"
      echo "         real/production config; any other name bootstraps the"
      echo "         dev/test node set in its own instance/NAME.sqlite -"
      echo "         see instance/config.json's DEFAULT_CONFIG for a"
      echo "         persistent default instead of passing -w every time)"
      echo "-r       reset wiring (both the legacy .pickle and the"
      echo "         actual .sqlite for the selected -w NAME)"
      exit 1
      ;;
    r)
      reset_wiring=1
      ;;
    w)
      wiring_file=$OPTARG
      ;;
    esac
  done

export AQUAPI_WIRING="${wiring_file}.pickle"
if [[ ${reset_wiring} ]]; then
  rm -f "instance/${wiring_file}.pickle" "instance/${wiring_file}.sqlite"
fi

export FLASK_APP=aquaPi
export FLASK_DEBUG=1

flask run --host "$(hostname -i|cut -d ' ' -f 1)"
