#!/usr/bin/bash

# Sorry for the inconvenience, but since this script has to be
# sourced it can't determine its own home (AFAIK)
MyHome=~/aquaPI

# 'basename $0' produces '-bash' on Debian/Rasberry OS ! why?? Skip the check!
if [[ ! "grep -i debian /usr/lib/os-release" ]]
then
  if [[ `basename $0` = "init" ]]
  then
    echo "ERROR: this script must be sourced: '. ${MyHome}/init'"
    fi
fi

if [[ ! -d ${MyHome}/venv ]]
then
  echo "First time init of aquaPi development env."
  read -p "CR to continue / Ctrl-C to cancel" dummy
  cd ${MyHome}
  # Debian derivatives don't come with py3 venv by default
  grep -i debian /usr/lib/os-release && sudo apt-get install python3-venv
  python3 -m venv venv
fi

echo "Activate aquaPi development env."
cd ${MyHome}
. ./venv/bin/activate
echo ===== get all python modules
pip3 install -r requirements.txt
echo =====

echo "To run the development server, use './run'"
echo "The debug server is 'http://localhost:5000'"
echo "'deactivate' will return to 'normal' - whatever that is ;-)"
