#!/usr/bin/env bash

topo_file='topo'
while getopts "hrt:" arg; do
  case $arg in
    h)
      echo "Parameters:"
      echo "-t TOPO  use TOPO.pickle to store topology"
      echo "-r       reset topology"
      exit 1
      ;;
    r)
      reset_topo=1
      ;;
    t)
      topo_file=$OPTARG
      ;;
    esac
  done

export AQUAPI_TOPO="${topo_file}.pickle"
if [[ ${reset_topo} ]]; then rm "instance/${AQUAPI_TOPO}"; fi

export FLASK_APP=aquaPi
export FLASK_ENV=development

nohup flask run --host "$(hostname -i|cut -d ' ' -f 1)" | tee logs/run.log
